MVC-Training1/Controllers/AddOrSubtractController.cs
using MVC_Training1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Training1.Controllers
{
    public class AddOrSubtractController : Controller
    {
        // GET: AddOrSubtract
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Result(AddOrSubtractModels data, string command) {
            if( command == "Add")
            {
                data.Result = data.FirstNumber + data.SecondNumber;
                data.Operation= "Sum";
            } else {

                data.Result = data.FirstNumber - data.SecondNumber;
                data.Operation = "Difference";
            }
            return View(data);
        }
    }
}

MVC-Training1/Views/AddOrSubtract/Index.cshtml
@model MVC_Training1.Models.AddOrSubtractModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add or Subtract</h2>
@using (Html.BeginForm("Result", "AddOrSubtract"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.FirstNumber)
        @Html.TextBoxFor(m => m.FirstNumber, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.SecondNumber)
        @Html.TextBoxFor(m => m.SecondNumber, new { @class = "form-control" })
    </div>
    <input type="submit" class="btn btn-primary" value="Add" name="command">
    <input type="submit" class="btn btn-success" value="Subtract" name="command">
}

MVC-Training1/Views/AddOrSubtract/Result.cshtml
@model MVC_Training1.Models.AddOrSubtractModels
@{
    ViewBag.Title = "Addition";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@(Model.Operation)</h2>
<ul>
    <li>
        @Model.Result
    </li>
</ul>