MVC-Training1/Controllers/ButtonColorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Training1.Controllers
{
    public class ButtonColorController : Controller
    {
        // GET: ButtonColor
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVC-Training1/Controllers/PaymentController.cs
using MVC_Training1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Training1.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        public ActionResult AddCard(Payment PaymentMode)
        {
            if (!ModelState.IsValid)
            {
                return View("AddCard", PaymentMode);

            }
            ModelState.Clear();
            return View();
        }
    }
}

MVC-Training1/Controllers/StoreController.cs
using MVC_Training1.Models;
using MVC_Training1.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;

namespace MVC_Training1.Controllers
{
    public class StoreController : Controller
    {
        private ApplicationDbContext _context;
        public StoreController()
        {
            _context = new ApplicationDbContext();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Store
        public ActionResult Index()
        {
            var list = _context.Stores.ToList();

            List<SelectListItem> listSelectListItem = new List<SelectListItem>();
            foreach(var item in list)
            {
                SelectListItem selectListItem = new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString(),
                };
                listSelectListItem.Add(selectListItem);
            }

            StoreViewModel storeViewModel = new StoreViewModel();
            storeViewModel.StoreModels = listSelectListItem;

            return View(storeViewModel);
        }
        public ActionResult view(StoreViewModel storeViewModel)
        {
            int ItemId = Convert.ToInt32(storeViewModel.SelectedItems);
            var ItemDetails = _context.Stores.SingleOrDefault(c => c.Id == ItemId);
            if (ItemDetails == null)
                return HttpNotFound();
            return View(ItemDetails);

        }
    }
}

MVC-Training1/Controllers/UserController.cs
using MVC_Training1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_Training1.Controllers
{
    public class UserController : Controller
    {
        public ActionResult Index(User user)
        {
            ModelState.Clear();
            return View();
        }
        public ActionResult Submit(User user)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", user);
            }
            HttpCookie userNameCookie = new HttpCookie("Name");

            userNameCookie.Values["Name"] = user.Name;

            userNameCookie.Expires = DateTime.Now.AddDays(30);

            Response.Cookies.Add(userNameCookie);

            return RedirectToAction("View", user);
        }
        public ActionResult View(User user)

        {
            if (!ModelState.IsValid)
            {
                return View("Index", user);
            }

            HttpCookie nameCookie = Request.Cookies["Name"];

            string name = nameCookie != null ? nameCookie.Value.Split('=')[1] : "undefined";

            TempData["Username"] = name;

            return View();
        }
    }
}

MVC-Training1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Button Color", "Index", "ButtonColor")</li>
                    <li>@Html.ActionLink("Add Or Subtract", "Index", "AddOrSubtract")</li>
                    <li>@Html.ActionLink("List Box", "Index", "Store")</li>
                    <li>@Html.ActionLink("Add Card", "AddCard", "Payment")</li>
                    <li>@Html.ActionLink("User Form", "Index", "User")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Training</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>